### ISSUE TITLE
Calculate entropy?

### ISSUE THREAD

**Issue by nomeata** [mikeizbicki/hmm#15]
I found you library while searching for code that would calculate the entropy of a hidden Markov model for me. The library does not provide it directly, it seems, but I was wondering if this is something you’d plan to add?

**Comment by mikeizbicki** [comment]
Sorry, no.  I haven't really been maintaining this library for a long time
and don't have any plans to improve it.

**Comment by nomeata** [comment]
Ok, thanks!
